# Generated by Django 3.2.3 on 2021-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Full Time', 'Full Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
