# Generated by Django 3.2.3 on 2021-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210602_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='jos/'),
        ),
    ]
