# Generated by Django 3.2.3 on 2021-05-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210525_2005'),
        ('job', '0005_job_category'),
    ]

    operations = [
    ]
